development:
  adapter: mysql
  database: DEVELOPMENT
  host: localhost
  username: DEVELOPMENT 
  password: 

test:
  adapter: mysql
  database: TEST
  host: localhost
  username: TEST 
  password: 

production:
  adapter: mysql
  database: portallus_production
  host: localhost
  username: portal_user
  password: bootlace 
